// Generated by CoffeeScript 1.6.3
var Ractive, RactiveCompiler, sysPath, umd;

Ractive = require('Ractive');

umd = require('umd-wrapper');

sysPath = require('path');

module.exports = RactiveCompiler = (function() {
  RactiveCompiler.prototype.brunchPlugin = true;

  RactiveCompiler.prototype.type = 'template';

  RactiveCompiler.prototype.extension = 'rac';

  RactiveCompiler.prototype.pattern = /\.(?:rac|ractive)$/;

  function RactiveCompiler(config) {
    this.config = config;
    null;
  }

  RactiveCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result;
    try {
      return result = umd(JSON.stringify(Ractive.parse(data)));
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  RactiveCompiler.prototype.include = [sysPath.join(__dirname, '..', 'vendor', 'Ractive.runtime-0.3.6.js')];

  return RactiveCompiler;

})();
